stages:
  - prepare
  # - validate
  # - transform

prepare-xmlstarlet-docker:
  stage: prepare
  image: docker:stable
  services:
    - docker:dind
  only:
    changes:
      - tooling/Dockerfile.xmlstarlet
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t "registry.gitlab.com/jirkavrba/semestralni-prace-4iz238/tooling:latest" - < ./tooling/Dockerfile.xmlstarlet
    - docker push "registry.gitlab.com/jirkavrba/semestralni-prace-4iz238/tooling:latest"