stages:
  - prepare
  - validate
  - transform
  - publish

prepare-tooling-dockerfile:
  stage: prepare
  image: docker:stable
  services:
    - docker:dind
  only:
    changes:
      - tooling/Dockerfile
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/jirkavrba/semestralni-prace-4iz238/tooling - < ./tooling/Dockerfile
    - docker push registry.gitlab.com/jirkavrba/semestralni-prace-4iz238/tooling

validate-xml-schema:
  stage: validate
  image: "registry.gitlab.com/jirkavrba/semestralni-prace-4iz238/tooling:latest"
  script:
    - xmlstarlet validate decks.xml # Validate source document
    - xmlstarlet validate decks.xsd # Validate schema document
    - xmlstarlet validate --xsd decks.xsd decks.xml # Validate the source documents against the schema

transform-xml-to-html:
  stage: transform
  image: "registry.gitlab.com/jirkavrba/semestralni-prace-4iz238/tooling:latest"
  needs:
    - validate-xml-schema
  script:
    - rm -f output/*.html
    - java -cp /opt/saxon/saxon-he-11.4.jar net.sf.saxon.Transform -xsl:xslt/html.xsl -s:decks.xml -o:output/index.html --allowSyntaxExtensions:off
  artifacts:
    expire_in: 1 hour
    paths:
      - output

transform-xml-to-pdf:
  stage: transform
  image: "registry.gitlab.com/jirkavrba/semestralni-prace-4iz238/tooling:latest"
  needs:
    - validate-xml-schema
  script:
    - rm -f output/*.pdf
    - fop -xml ./decks.xml -xsl ./xslt/pdf.xsl -pdf ./output/decks.pdf -param root "$(pwd)/xslt"
  artifacts:
    expire_in: 1 hour
    paths:
      - output
    
pages:
  stage: publish
  needs:
    - transform-xml-to-html
    - transform-xml-to-pdf
  script:
    - cp -r output public
  artifacts:
    paths:
      - public
  
