stages:
  - prepare
  # - validate
  - transform

prepare-tooling-dockerfile:
  stage: prepare
  image: docker:stable
  services:
    - docker:dind
  only:
    changes:
      - tooling/Dockerfile
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/jirkavrba/semestralni-prace-4iz238/tooling - < ./tooling/Dockerfile
    - docker push registry.gitlab.com/jirkavrba/semestralni-prace-4iz238/tooling

# validate-xml-schema:
#   stage: validate
#   image: "registry.gitlab.com/jirkavrba/semestralni-prace-4iz238/tooling:latest"

transform-xml-to-html:
  stage: transform
  image: "registry.gitlab.com/jirkavrba/semestralni-prace-4iz238/tooling:latest"
  only:
    changes:
      - decks.xml
      - xslt/html.xsl
  script:
    - rm -f output/*.html
    - xslt -s:decks.xml -xsl:xslt/html.xsl -o:output/index.html --allowSyntaxExtensions:off